
# models 
base_model: "deepset/roberta-base-squad2"
encoder: 'sentence-transformers/sentence-t5-base'
optim: 'Adam'
scheduler: 'cosine'
log_file: 'train.log'

# dataset split
test_points: 425 

# hyperparameters
n_epochs: 5
lr: 0.0001
eps: 0.00005
batch_size: 4
